name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'  # You can use any Go version you prefer

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test

      - name: Run static analysis with GolangCI-Lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-1.50.1-linux-amd64.tar.gz | tar -xzv
          mv golangci-lint-1.50.1-linux-amd64/golangci-lint /usr/local/bin
          golangci-lint run

      - name: Run dynamic analysis with OWASP ZAP
        run: |
          docker run -u 0 -v $PWD:/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py -t http://localhost:8080
