name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

      - name: Generate test coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out

      - name: Build application
        run: go build -v .

      - name: Install GoSec
        run: |
          curl -sSL https://github.com/securego/gosec/releases/download/v2.15.0/gosec_2.15.0_linux_amd64.tar.gz -o gosec.tar.gz
          tar -xvf gosec.tar.gz -C /usr/local/bin gosec
          chmod +x /usr/local/bin/gosec

      - name: Run static analysis with GoSec
        run: gosec -fmt=verbose ./...

      - name: Start Application
        run: |
          go run main.go &
          sleep 30  # Wait for the application to fully start

      - name: OWASP ZAP Security Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'http://localhost:8080'
